OficioMVC/Models/Siga_profs.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace OficioMVC.Models
{
    public class Siga_profs
    {

        [JsonProperty("ID")]
        
        public int ID { get; set; }
        [Required]
        [Display(Name ="Usuario de login é obrigatorio!")]
        public string user_login { get; set; }

        [Required]
        [Display(Name = "Senha está vazia!")]
        [JsonProperty("user_pass")]
        public string user_pass { get; set; }
        [JsonProperty("user_nicename")]
        public string user_nicename { get; set; }
        [JsonProperty("ativo")]
        public string ativo { get; set; }
        [JsonProperty("dpto")]
        public string dpto { get; set; }
        public bool master { get; set; }
        public ICollection<Documento> Documentos { get; set; } = new List<Documento>();

        public Siga_profs(int iD, string user_login, string user_pass, string user_nicename, string ativo, string dpto)
        {
            ID = iD;
            this.user_login = user_login ;
            this.user_pass = user_pass ;
            this.user_nicename = user_nicename ;
            this.ativo = ativo;
            this.dpto = dpto;
            this.master = false;
        }
        public Siga_profs(int iD, string user_login, string user_pass, string user_nicename, string ativo, string dpto,bool Master)
        {
            ID = iD;
            this.user_login = user_login;
            this.user_pass = user_pass;
            this.user_nicename = user_nicename;
            this.ativo = ativo;
            this.dpto = dpto;
            this.master = Master;
        }
        public Siga_profs()
        {

        }
    }
    }

OficioMVC/Controllers/Siga_profsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OficioMVC.Models;
using OficioMVC.Models.ViewModels;
using OficioMVC.Service;

namespace OficioMVC.Controllers
{
    public class Siga_profsController : Controller
    {
        private readonly OficioMVCContext _context;
        private readonly Siga_profsService _profsService;
        private readonly HashPass _hash;

        public Siga_profsController(OficioMVCContext context, Siga_profsService profsService, HashPass hash)
        {
            _context = context;
            _profsService = profsService;
            _hash = hash;
        }



        public async Task<IActionResult> Verify(String user_login)
        {
            if (user_login == null)
            {
                return NotFound();
            }
            

            var siga_profs = await _context.Siga_profs
                .FirstOrDefaultAsync(m => m.user_login == user_login);
            if (siga_profs == null)
            {
                return NotFound();
            }

            return View(siga_profs);
        }

        public IActionResult Authorization(int id)
        {
            ViewBag.id = id;
            return View();
        }

        [HttpPost]
        public IActionResult Authorization(int Id, Siga_profs Usuario)
        {
            string HashPass = _hash.GerarMD5(Usuario.user_pass);
            var obj = _profsService.FindByUser(Usuario.user_login, HashPass);
            if (obj != null)
            {
                if (_profsService.Siga_profsExists(obj.ID) && obj.master == true)
                {
                    return RedirectToAction("Edit", "Documentos", new { Id = Id, authorization = true });
                }
            }

           

            return RedirectToAction("Error","Documentos", new { message = "Acesso negado" });
        }

    }
}

OficioMVC/Views/Siga_profs/Authorization.cshtml
@model OficioMVC.Models.ViewModels.EditarDocumentoViewModel;

@{
    ViewData["Title"] = "Editar documento - Liberação";
}







        @section Scripts
        {
            <script src="~/js/ModalScript/Modal.js"></script>
            <script>
                let modal = document.getElementById('myModalSucess');
                     window.onload = function () {
                 abrirModal(modal);
                }

               
        $("#myModalSucess").on('hidden.bs.modal', function (){
            window.history.back();
        });
            </script>   
        }


<!-- Modal HTML Sucesso -->
<div id="myModalSucess" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Autorização </h4>
                 <button class='btn btn-danger offset-md-7'onClick="fecharModal(modal)">Fechar</button>
            </div>
            <div class="modal-body">
               <h4>Informe usuario e senha</h4>
            <hr />
            <div class="container">
                <div class="col-md-12 ">
                    <form class="form-new" asp-action="authorization" asp-controller="Siga_profs">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="id" id="input-id"  value="@ViewBag.id"/>
                        <div class="col-md-12">
                            Usuário
                            <input type="text" asp-for="Usuario.user_login" class="form-control pt-2"/>
                            <span asp-validation-for="Usuario.user_login" class="text-danger"></span>
                        </div>
                        <div class="col-md-12">
                            Senha
                            <input asp-for="Usuario.user_pass" class="form-control pt-2" type="password" />
                            <span asp-validation-for="Usuario.user_pass" class="text-danger"></span>
                        </div>
                        
                        <div class="col-md-12 pt-3">
                                <button id ="btnLogin"class="btn btn-lg btn-primary " type="submit">Entre</button>
                        </div>
                    </form>
                </div>
            </div>
            </div>
            <div class="modal-footer">
              
            </div>
        </div>
    </div>

        }

    }
}

OficioMVC/Views/Siga_profs/LiberaAcesso.cshtml
@model OficioMVC.Models.Siga_profs

@{
    ViewData["Title"] = "LiberaAcesso";
    int id = @ViewBag.id;
}

<h2>LiberaAcesso</h2>

<h4>Siga_profs</h4>
<hr />
<div class="container-fluid" id="fundoLogin">
    <h2 class="d-flex justify-content-center h-100 ">@ViewData["Title"]</h2>
    <div class="d-flex justify-content-center h-100 w-100 ">
        <div class="card ">
            <div class="card-header">
                <h3>Entre</h3>
                <div class="d-flex justify-content-end social_icon">
                </div>
            </div>
            <div class="card-body ">
                <form asp-action="LiberaAcesso">

                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class=""></i></span>
                        </div>
                        <input type="text" asp-for="user_login" class="form-control" placeholder="Login" required>
                        <span asp-validation-for="user_login" class="text-danger"></span>

                    </div>
                    <div>
                        @*<input type="text" asp-for="ID"*@
                    </div>
                    <div class="input-group form-group ">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class=""></i></span>
                        </div>
                        <input type="password" asp-for="user_pass" class="form-control" placeholder="Senha" required>
                        <span asp-validation-for="user_pass" class="text-danger row-md-2"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="LiberaAcesso" class=" float-right  btn btn-success">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<div>
    <a asp-action="Index">Back to List</a>
</div>